clear @a red_bundle
clear @a orange_bundle
clear @a yellow_bundle
clear @a lime_bundle
clear @a green_bundle
clear @a cyan_bundle
clear @a light_blue_bundle
clear @a blue_bundle
clear @a purple_bundle
clear @a magenta_bundle
clear @a pink_bundle
clear @a brown_bundle
clear @a black_bundle
clear @a gray_bundle
clear @a light_gray_bundle
clear @a white_bundle
clear @a bundle