export default [
    {
        name: `建材`,
        lore: `building material`,
        icon: `minecraft:oak_log`,
        items: [
            { id: `minecraft:oak_log`, price: 4 },
            { id: `minecraft:acacia_log`, price: 4 },
            { id: `minecraft:birch_log`, price: 4 },
            { id: `minecraft:cherry_log`, price: 4 },
            { id: `minecraft:dark_oak_log`, price: 4 },
            { id: `minecraft:jungle_log`, price: 4 },
            { id: `minecraft:mangrove_log`, price: 4 },
            { id: `minecraft:spruce_log`, price: 4 },
            { id: `minecraft:pale_oak_log`, price: 4 },
            { id: `minecraft:gravel`, price: 4 },
            { id: `minecraft:white_concrete`, price: 4 },
            { id: `minecraft:white_concrete_powder`, price: 4 },
            { id: `minecraft:glass`, price: 4 },
            { id: `minecraft:quartz_block`, price: 4 },
            { id: `minecraft:sandstone`, price: 4 },
            { id: `minecraft:brick_block`, price: 4 },
            { id: `minecraft:stonebrick`, price: 4 },
            { id: `minecraft:cobblestone`, price: 4 },
            { id: `minecraft:cobbled_deepslate`, price: 4 },
            { id: `minecraft:white_wool`, price: 4 },
            { id: `minecraft:hardened_clay`, price: 4 },
            { id: `minecraft:white_terracotta`, price: 8 },
            { id: `minecraft:light_gray_terracotta`, price: 8 },
            { id: `minecraft:gray_terracotta`, price: 8 },
            { id: `minecraft:black_terracotta`, price: 8 },
            { id: `minecraft:brown_terracotta`, price: 8 },
            { id: `minecraft:red_terracotta`, price: 8 },
            { id: `minecraft:orange_terracotta`, price: 8 },
            { id: `minecraft:yellow_terracotta`, price: 8 },
            { id: `minecraft:lime_terracotta`, price: 8 },
            { id: `minecraft:green_terracotta`, price: 8 },
            { id: `minecraft:cyan_terracotta`, price: 8 },
            { id: `minecraft:light_blue_terracotta`, price: 8 },
            { id: `minecraft:blue_terracotta`, price: 8 },
            { id: `minecraft:purple_terracotta`, price: 8 },
            { id: `minecraft:magenta_terracotta`, price: 8 },
            { id: `minecraft:pink_terracotta`, price: 8 },
            { id: `minecraft:calcite`, price: 8 },
            { id: `minecraft:pale_moss_block`, price: 8 },
            { id: `minecraft:pale_hanging_moss`, price: 8 },
            { id: `minecraft:prismarine_bricks`, price: 8 },
            { id: `minecraft:brick`, price: 2 },
            { id: `minecraft:netherbrick`, price: 3 },
        ]
    },
    {
        name: `食べ物`,
        lore: `food`,
        icon: `minecraft:bread`,
        items: [
            { id: `minecraft:cooked_beef`, price: 400 },
            { id: `minecraft:apple`, price: 200 },
            { id: `minecraft:bread`, price: 250 },
            { id: `mc:basil`, price: 20 },
            { id: `mc:onion`, price: 100 },
            { id: `mc:garlic`, price: 60 },
            { id: `mc:ovlive`, price: 75 },
            { id: `mc:tomato`, price: 75 },
            { id: `mc:pepper`, price: 30 },
            { id: `mc:salt`, price: 15 },
            { id: `mc:mikan`, price: 300 },
            { id: `mc:adzuki_beans`, price: 20 },
            { id: `mc:squid`, price: 60 },
            { id: `mc:sweet_corn`, price: 90 },
            { id: `mc:pineapple`, price: 600 },
            { id: `minecraft:egg`, price: 20 },
            { id: `mc:straw_berry`, price: 120 },
            { id: `mc:mikan`, price: 400 },
            /*{ id: `mc:xmas_chicken`, price: 1500 },
            { id: `mc:pizza`, price: 2000 },
            { id: `mc:osechi`, price: 2200 },
            { id: `mc:omochi`, price: 500 },
           */
        ]
    },
    {
        name: `鍛冶型`,
        lore: `smithing template`,
        icon: `minecraft:netherite_upgrade_smithing_template`,
        items: [
            { id: `minecraft:netherite_upgrade_smithing_template`, price: 3000 },
            { id: `minecraft:spire_armor_trim_smithing_template`, price: 50000 },
            { id: `minecraft:snout_armor_trim_smithing_template`, price: 50000 },
            { id: `minecraft:rib_armor_trim_smithing_template`, price: 50000 },
        ]
    },
    {
        name: `モブドロップ`,
        lore: `mob drop item`,
        icon: `minecraft:bone`,
        items: [
            { id: `minecraft:blaze_rod`, price: 300 },
            { id: `minecraft:magma_cream`, price: 300 },
            { id: `minecraft:shulker_shell`, price: 600 },
        ]
    },
    {
        name: `農業`,
        lore: `agriculture`,
        icon: `minecraft:carrot`,
        items: [
            { id: `mc:rice_seed`, price: 25 },
            { id: `minecraft:potato`, price: 25 },
            { id: `minecraft:carrot`, price: 25 },
            { id: `minecraft:beetroot_seeds`, price: 25 },
            { id: `minecraft:pumpkin_seeds`, price: 25 },
            { id: `minecraft:melon_seeds`, price: 25 },
            { id: `mc:soybeans`, price: 50 },
            { id: `minecraft:cherry_sapling`, price: 50 },
            { id: `minecraft:acacia_sapling`, price: 50 },
            { id: `minecraft:birch_sapling`, price: 50 },
            { id: `minecraft:dark_oak_sapling`, price: 50 },
            { id: `minecraft:jungle_sapling`, price: 50 },
            { id: `minecraft:oak_sapling`, price: 50 },
            { id: `minecraft:pale_oak_sapling`, price: 50 },
            { id: `minecraft:spruce_sapling`, price: 50 },
            { id: `minecraft:dandelion`, price: 10 },
            { id: `minecraft:poppy`, price: 10 },
            { id: `minecraft:blue_orchid`, price: 10 },
            { id: `minecraft:allium`, price: 10 },
            { id: `minecraft:azure_bluet`, price: 10 },
            { id: `minecraft:red_tulip`, price: 10 },
            { id: `minecraft:orange_tulip`, price: 10 },
            { id: `minecraft:white_tulip`, price: 10 },
            { id: `minecraft:pink_tulip`, price: 10 },
            { id: `minecraft:oxeye_daisy`, price: 10 },
            { id: `minecraft:cornflower`, price: 10 },
            { id: `minecraft:lily_of_the_valley`, price: 10 },
            { id: `minecraft:sunflower`, price: 10 },
            { id: `minecraft:lilac`, price: 10 },
            { id: `minecraft:rose_bush`, price: 10 },
            { id: `minecraft:peony`, price: 10 },
            { id: `minecraft:pink_petals`, price: 10 },
            { id: `mc:coffee_beans`, price: 20 },
        ]
    },
    {
        name: `その他`,
        lore: `other`,
        icon: `minecraft:netherrack`,
        items: [
            { id: `minecraft:quartz`, price: 1 },
            { id: `minecraft:warped_fungus`, price: 40 },
            { id: `minecraft:crimson_fungus`, price: 40 },
            { id: `minecraft:soul_soil`, price: 4 },
            { id: `minecraft:soul_sand`, price: 4 },
            { id: `minecraft:warped_nylium`, price: 4 },
            { id: `minecraft:crimson_nylium`, price: 4 },
            { id: `minecraft:netherrack`, price: 4 },
            { id: `minecraft:blackstone`, price: 4 },
            { id: `minecraft:basalt`, price: 10 },
            { id: `minecraft:ancient_debris`, price: 10000 },
            { id: `minecraft:sponge`, price: 100 },
            { id: `minecraft:glowstone`, price: 40 },
            { id: `minecraft:purpur_block`, price: 10 },
            { id: `minecraft:end_stone`, price: 4 },
            { id: `minecraft:prismarine`, price: 4 },
            { id: `minecraft:crimson_stem`, price: 6 },
            { id: `minecraft:warped_stem`, price: 6 },
            { id: `minecraft:sculk`, price: 500 },
            { id: `minecraft:sculk_catalyst`, price: 50 },
            { id: `minecraft:mycelium`, price: 400 },
            { id: `minecraft:cactus`, price: 2000 },
        ]
    },
    {
        name: `その他2`,
        lore: `other 2`,
        icon: `minecraft:torch`,
        items: [
            { id: `minecraft:torch`, price: 10 },
            { id: `minecraft:lantern`, price: 20 },
            { id: `minecraft:sea_lantern`, price: 20 },
            { id: `minecraft:experience_bottle`, price: 100 },
            { id: `minecraft:mace`, price: 300000 },
            { id: `minecraft:elytra`, price: 150000 },
            { id: `minecraft:heart_of_the_sea`, price: 50000 },
            { id: `minecraft:nether_wart`, price: 300 },
            { id: `minecraft:lead`, price: 300 },
            { id: `minecraft:name_tag`, price: 400 },
            { id: `minecraft:end_rod`, price: 15 },
            { id: `minecraft:blue_ice`, price: 15 },
            { id: `minecraft:music_disc_pigstep`, price: 2000 },
        ]
    },
    {
        name: `ロビーへ戻る`,
        lore: `other 2`,
        icon: `minecraft:command_block`,
        items: [
            { id: `minecraft:command_block`, price: 0.000001},
        ]
    },
    {
        name: `硬貨・お札`,
        lore: `money`,
        icon: `money:bill_1000`,
        items: [
            { id: `money:coin_1`, price: 1 },
            { id: `money:coin_10`, price: 10 },
            { id: `money:coin_50`, price: 50 },
            { id: `money:coin_100`, price: 100 },
            { id: `money:coin_500`, price: 500 },
            { id: `money:bill_1000`, price: 1000 },
            { id: `money:bill_5000`, price: 5000 },
            { id: `money:bill_10000`, price: 10000 },
        ]
    },
];
